language: node_js
node_js: '10'

env:
    global:
        - FORCE_COLOR=1

cache: yarn

script:
    - npm run prettier
    - npm run build

deploy:
    - provider: script
      skip_cleanup: true
      script: npm run semantic-release
